version: "3"

services:
  greeter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${USER}    # Environment variables mapped to build args
        - GROUP=${GROUP}  # See above
    container_name: greeter
    command: greeter -l /log/user.log root $USER # user that checked from the script
    environment:
      - USER=$USER      # Current host user which runs the docker-compose command
      - GROUP=$USER     # See above
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - pers_log:/log:rw
    restart: unless-stopped

volumes:
  pers_log:
